### ISSUE TITLE
QT file not found!

### ISSUE THREAD

**Issue by NothingCw** [YanShulinjj/Sample-Compiler#1]
from MainUI import  Ui_MainWindow
from VocaWindow import  Ui_self
QT file not found!
Please upload this

**Comment by YanShulinjj** [comment]
Now try it again.

**Comment by YanShulinjj** [comment]
> from MainUI import Ui_MainWindow
> from VocaWindow import Ui_self
> QT file not found!
> Please upload this

Now try it again.
